# Generated by Django 6.0.2 on 2026-03-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misfinanzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='monto',
            field=models.FloatField(),
        ),
    ]
