# Generated by Django 6.0.2 on 2026-02-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misfinanzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='precio',
            field=models.FloatField(),
        ),
    ]
